### ISSUE TITLE
The Rating component behaves the same way with or without Transition

### ISSUE THREAD

**Issue by bmonish** [awran5/react-simple-star-rating#1]
```
<Rating
        onClick={(e) => {}}
        ratingValue={5}
        size={20}
        fillColor="orange"
        className="foo" // Will remove the inline style if applied
     />
     
     
```
and 
```
<Rating
        onClick={(e) => {}}
        ratingValue={5}
        size={20}
        fillColor="orange"
        transition
        className="foo" // Will remove the inline style if applied
      />
```

Behaves the same way

**Comment by awran5** [comment]
Hi @bmonish Because it is the default action. If you like to disable the transition, just add `false` to the `transition` prop 
```tsx
transition={false}
```

**Comment by bmonish** [comment]
Just now I tried to add ``` transition={false} ``` But still the bug remains

**Comment by awran5** [comment]
Hi @bmonish 
Sorry for the late answer. Would you please check this [sandBox](https://codesandbox.io/s/react-simple-star-rating-ts-fzmpu) and see if it works properly?

**Comment by bmonish** [comment]
![image](https://user-images.githubusercontent.com/31185862/122587892-08608f00-d07c-11eb-86ee-e4ba9738a909.png)

I guess still the problem exists! On the right side I was just hovering

**Comment by awran5** [comment]
I guess I see the issue now. I thought you're talking about the `css transition` effect not the whole `hover` effect it self. I'll add the option to disable the hover effect in the next release but I'm afraid that will take some time till I can get some free time.

Meanwhile, I've created another [sandbox](https://codesandbox.io/s/react-simple-rating-ts-forked-xu3wm) with hover effect is completely removed, feel free to use/edit as a local component in your project.

I hope that solution will work for you.

**Comment by bmonish** [comment]
Sure! Thank you so much!
