### ISSUE TITLE
v4.1.0 doesn't include dist/ on npm

### ISSUE THREAD

**Issue by phibr0** [awran5/react-simple-star-rating#24]
When downloading v4.1.0 from npm, only the following files are included:

```
react-simple-star-rating/
├── LICENSE
├── README.md
└── package.json
```

Also please take a look at [semver.org](https://semver.org/). Because of the breaking API Changes, this update should have been a major release.

**Comment by awran5** [comment]
@phibr0  My bad, I'm using standard-version for auto versioning which is seem deprecated now. I published a new 5.0.0 version please check it out.

Thank you for pointing that out.
