### ISSUE TITLE
Window is not defined error

### ISSUE THREAD

**Issue by laura-sgn** [awran5/react-simple-star-rating#28]
I'm using version 5.1.2 with Next.js but the error `Server Error ReferenceError: window is not defined` is thrown when trying to use this component. I'm aware this was a [closed issue](https://github.com/awran5/react-simple-star-rating/issues/26) but the problem has not been resolved.

**Comment by awran5** [comment]
Hello @laura-sgn. Please check the latest release.

Thank you.

**Comment by laura-sgn** [comment]
Fix worked! Thank you.
