### ISSUE TITLE
I can change the star SVG?

### ISSUE THREAD

**Issue by Albuquerquess** [awran5/react-simple-star-rating#3]

**Comment by awran5** [comment]
Hi @Albuquerquess 

Yes, you can now please check out v2.

**Comment by Albuquerquess** [comment]
can you send me the link, pls?

Em seg, 5 de jul de 2021 17:49, Ahmed Khalil ***@***.***>
escreveu:

**Comment by awran5** [comment]
Its just uploaded to the [npm](https://www.npmjs.com/package/react-simple-star-rating) 

just use:

```sh
npm i react-simple-star-rating
```

or Yarn

```sh
yarn add react-simple-star-rating
```

then follow this simple instructions about how to add a [custom SVG](https://github.com/awran5/react-simple-star-rating#custom-svg)
