### ISSUE TITLE
Is there a way to turn off the hover alt text '18.75 out of 4' ?

### ISSUE THREAD

**Issue by ching** [awran5/react-simple-star-rating#32]
Hi there! 

I would like to use this component and adjust the iconsCount to less than 5. However, the alt text is calculated as percentages by default. So instead of 3 out of 4 given iconsCount of 4, it displays as 18.75 out of 4 (which is quite confusing for the user). 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3440261/203171303-222dab2f-786d-4258-80a1-a8c60d4f687e.png">

Here is the code used:

```
<Rating
    onClick={handleRating2}
    transition
    iconsCount={4}
    size={50}
/>
```

Please advise! Thank you!

**Comment by awran5** [comment]
Hi @ching 

Just release a new [v5.1.7](https://github.com/awran5/react-simple-star-rating/compare/v5.1.7...v5.1.7) to fix this with an option to disable the title tag if you want.

```jsx
<Rating allowTitleTag={false} {/* ... */ }/>
```

Please test and let me know.

Thank you.

**Comment by ching** [comment]
Confirmed that it is fixed - thanks!
