### ISSUE TITLE
Doesn't work on mobile browsers

### ISSUE THREAD

**Issue by victoriaSh** [awran5/react-simple-star-rating#6]
Hello,
I've tried it on my website and it doesn't work on mobile browsers (iOS, Chrome and Safari). 
Demo doesn't work either.

**Comment by awran5** [comment]
Hello @victoriaSh Thank you for bringing that to my attention! I just pushed a fix for this issue. Please try it out and let me know.

**Comment by victoriaSh** [comment]
Wow, that you for a quick response! I've tried last 4.0.2 version and it doesn't work correctly. Sometimes I can set rating only on a long touch or double tap, sometimes not. Setting rating on a click doesn't work.

**Comment by awran5** [comment]
Hi @victoriaSh  

**Edited**

Actually that was the intended action, you start a touch on the rating area, hold and move your finger to select a value and it will be set when your finger (touch) leave the rating icons (applies only to mobile devices). Would you please describe how it should work like a better approach.

**Comment by awran5** [comment]
Hello @victoriaSh 

I think I understand the problem now. Please try the latest version 4.0.3

Thank you.

**Comment by victoriaSh** [comment]
Now it works perfectly. Thank you!

The only thing, it would be better to add `-webkit-tap-highlight-color: transparent;` to root element by default to hide blue background on touch on mobile devices.
