### ISSUE TITLE
Can't reset ratingValue

### ISSUE THREAD

**Issue by CharlieGroves** [awran5/react-simple-star-rating#7]
I have the rating as a part of a form, which when submitted eventually resets the star rating but the rating is not being reactive:
						
`const handleReview = (e) => {
        ...
        setRating(0);
        ...
};`

`<Rating
	allowHalfIcon
	onClick={handleRating}
	ratingValue={rating}
/>`

Is there a different way to do this?

**Comment by awran5** [comment]
Hello @CharlieGroves 

Sorry for the late response.  I just pushed a fix that should fix this issue. Please follow this [example](https://react-simple-star-rating.vercel.app/#handle-reset) and let me know if it fixed.

**Comment by CharlieGroves** [comment]
Thank you!
