### ISSUE TITLE
[v4] Display vertically by default

### ISSUE THREAD

**Issue by jorgemasta** [awran5/react-simple-star-rating#9]
Thanks so much for this project!

I just installed it but the v4 is rendering the stars vertically, so it's not usable. If I install version 3.0.0 it works as expected.

**Comment by reallybeard** [comment]
My theme was overriding all svgs with `display: block;` 

i'm not sure if this styling was removed or what happened but you can fix it by doing

```
svg.star-svg {
    display: inline;
}
```

**Comment by jasonpraful** [comment]
Thanks for the tip @reallybeard ! I had the same issue, that comment helped. Created a new PR to fix this issue.

**Comment by IhsenBen** [comment]
thx for the tip @reallybeard, I was going through the same issue without any customer theme conflict.
the issue is still up

**Comment by iiaan** [comment]
i have the same problem, it appears vertically, how can i solve it?

**Comment by IhsenBen** [comment]
> i have the same problem, it appears vertically, how can i solve it?

you have to modify the css class manually.
the answer is just above Ian...

**Comment by jasonpraful** [comment]
This has been fixed.
https://github.com/awran5/react-simple-star-rating/pull/14

**Comment by jasonpraful** [comment]
@jorgemasta or @awran5  - Can you please close this Issue :)

**Comment by Vladimir-art** [comment]
The same issue with 5.1.7 version

**Comment by CascadeColin** [comment]
@reallybeard's solution works if you have any CSS display setting cascading into the component.  It was `display: flex` cascading down in my case, and probably is the same for many others finding this thread.

**Comment by TechGitMaster** [comment]
In my case I just added 'SVGstyle={ { 'display':'inline' } }' and it work. The version I used was 5.1.6
![image](https://github.com/awran5/react-simple-star-rating/assets/52535645/e4baf7ca-de00-4076-a2fc-3e83e1bdc59d)

**Comment by hktom** [comment]
You can just add SVGstyle={{ display: "inline" }}

**Comment by arifikhsan** [comment]
using tailwind is adding SVGclassName="inline"

![image](https://github.com/awran5/react-simple-star-rating/assets/32485694/46135730-1edc-4056-93f3-f6686f5bf6f6)
